### PR TITLE
Some early instructions on how to handle schema changes

### PR DESCRIPTION
**Pull request by EdwardKaravakis**

### CODE REVIEW

**Comment by tmaeno** [comment]
It would be better to consolidate all docs in https://github.com/PanDAWMS/panda-docs that are built to https://panda-wms.readthedocs.io/en/latest/ , rather than putting them in individual repositories separately. Harvester has its own doc in the repository since it is "officially" independent of PanDA, but that is not the case for panda-database.

**Comment by EdwardKaravakis** [comment]
Absolutely, I will point to https://panda-wms.readthedocs.io/en/latest/ for instructions and then update the panda-docs module

**Comment by tmaeno** [comment]
Correct.

**Comment by EdwardKaravakis** [comment]
OK good, thanks, will merge this (as it just adds a pointer to the official docs) and will work on the docs.

**Pull request merged**
