### PR TITLE
Adding "is_expert" column to DOMA_PANDABIGMON.AUTH_USER table

### PR DESCRIPTION
**Pull request by Foorth**

### CODE REVIEW

**Comment by EdwardKaravakis** [comment]
Hi @Foorth ,
the "is_expert" column needs to be also in the schema (for new installations) for the doma_pandabigmon.auth_user table - and the same changes (schema and upgrade diff script) needs to be there for oracle as well. Thanks!

**Comment by Foorth** [comment]
@EdwardKaravakis , done.

**Comment by EdwardKaravakis** [comment]
One last thing: could you please rename schema/oracle/sqls/patches/0.0.1.patch.sql to schema/oracle/sqls/patches/0.0.14.patch.sql ? The schema versions need to be the same for both oracle and postgres. Thanks!

**Comment by Foorth** [comment]
@EdwardKaravakis , do you mean this schema: doma_pandabigmon?

**Comment by EdwardKaravakis** [comment]
I mean the file name in oracle, it should follow the schema version number and it is not 0.0.1, since you've increased it, it should be 0.0.14

**Comment by Foorth** [comment]
@EdwardKaravakis , done.

**Comment by EdwardKaravakis** [comment]
Perfect, thanks! Let me also do one last change and I will accept it - thanks!

**Comment by EdwardKaravakis** [comment]
Ok I have increased the schema version for oracle and pg to 0.0.14 - from now on, there is no need to increase the schema version for one small alter - for example we could edit the same 0.0.14 patch file and add there our required changes - it could contain your changes, my changes, fernando's and etc.

**Comment by EdwardKaravakis** [comment]
Merging, thanks!

**Pull request merged**
