### PR TITLE
Improve postgres deployment

### PR DESCRIPTION
**Pull request by EdwardKaravakis**
Changed the schema for the pandadb_version in postgres from public to doma_panda so we won't have to patch the WrappedCursor in pandaserver/taskbuffer

The issue was coming from the fact that previously the postgres init script was creating the pandadb_version in the public schema and not in the doma_panda. Which in principle it is fine but then the WrappedCursor in pandaserver/taskbuffer was adding the panda_config.schema in the query and a simple `select * from doma_panda.pandadb_version;` fails. The only way to make it work was by patching the WrappedCursor to remove `doma_panda.` from the query that checks the pandadb version schema.

Now the init script creates this table in the doma_panda schema and not in the public schema

### CODE REVIEW

**Comment by tmaeno** [comment]
I had a look at the long conversation in JIRA about testing. Even if you ask me to review, I don't go through all the details in the changes or don't test them by myself. I point out something obviously wrong. You are responsible for guaranteeing that the changes work out of the box. A couple of things.

* If pandadb_version is in the panda schema, shouldn't it go to [ pg_PANDA_TABLE.sql](https://github.com/PanDAWMS/panda-database/blob/ATLASPANDA-657/schema/postgres/sqls/pg_PANDA_TABLE.sql) ? Is there any reason why it must be defined in init_step.sql?

* Have you tested your changes with image+k8s? I don't see an image for ATLASPANDA-657 at [the container image page](https://github.com/PanDAWMS/panda-database/pkgs/container/panda-database). Basically, I always test my changes in this repository by making images in [my fork](https://github.com/tmaeno/panda-database2/pkgs/container/panda-database2) and deploying them on OKD.

**Comment by EdwardKaravakis** [comment]
> I had a look at the long conversation in JIRA about testing. Even if you ask me to review, I don't go through all the details in the changes or don't test them by myself. I point out something obviously wrong. You are responsible for guaranteeing that the changes work out of the box. A couple of things.
> 
Hi Tadashi,
Of course I do not expect you to test my changes - and yes, I have tested my changed on postgres. They were working out of the box for postgres but not on ADCR. The problem is that I did not know that after my tests and your review, by merging into master, my changes will be deployed in production - I thought we were using releases in production... at least I could see the releases in the github module page and I thought that this is how we deploy new versions in productions. 

>     * If pandadb_version is in the panda schema, shouldn't it go to [ pg_PANDA_TABLE.sql](https://github.com/PanDAWMS/panda-database/blob/ATLASPANDA-657/schema/postgres/sqls/pg_PANDA_TABLE.sql) ? Is there any reason why it must be defined in init_step.sql?
I have modified the way you were doing it, that is why it is in init_step.sql and not in pg_PANDA_TABLE.sql - the only reason why it is now in the panda schema is because I need to have the schema name in the query (otherwise ADCR Oracle Production fails) - if you want me to change it, I will change it.
> 
>     * Have you tested your changes with image+k8s? I don't see an image for ATLASPANDA-657 at [the container image page](https://github.com/PanDAWMS/panda-database/pkgs/container/panda-database). Basically, I always test my changes in this repository by making images in [my fork](https://github.com/tmaeno/panda-database2/pkgs/container/panda-database2) and deploying them on OKD.
Yes I did test them, I built and pushed my own image on docker hub..

**Comment by tmaeno** [comment]
My stuff was only for postgres and thus it was enough to have it in the public schema.  If it needs to move to the panda schema better to have the definition in pg_PANDA_TABLE.sql instead of init_step.sql.

**Comment by EdwardKaravakis** [comment]
OK, I will move the creation of the table on the pg_PANDA_TABLE.sql file - you are right, this is cleaner.

**Review by tmaeno — APPROVED** [review]

**Comment by EdwardKaravakis** [comment]
@tmaeno I have also modified panda_db_init.sh script to follow your suggestion https://github.com/PanDAWMS/panda-database/pull/5/commits/a5172b3e5aa6969d0d36e138c7080a992634c1cd
Unfortunately the cern k8s cluster is not responding at the moment, please review the change but do not yet merge this PR before I fully test it:
`
[ekaravak@lxplus8s19 ~]$ kubectl get all 

Unable to connect to the server: dial tcp 188.185.124.30:6443: i/o timeout
`

**Review by tmaeno — APPROVED** [review]

**Pull request merged**
